### PR TITLE
Restructure cfgs

### PR DESCRIPTION
**Pull request by Tekaoh**
I propose an adjusted approach to configs.

* Default settings live in servercommon.cfg
* Settings that need to be populated by build.xml live in localOptions.cfg

* localOptions is no longer tracked by git. Instead, there is a template file that is tracked.
* `ant swg` will copy the template out to create localOptions.cfg and populate it with needed values
* Users should only change settings in localOptions.cfg. These settings can be copied from servercommon.cfg and can override defaults

* By only having users change an untracked file, git will have no problem pulling updates from the config repo without getting mad about settings that a user might have changed.
* By having tracked files that will never be changed by the user locally, devs can add new config flags and they will be pulled to existing VMs when they look for updates

* Other files that are not included by servercommon.cfg and are not used by default have been renamed as templates so that if users want them, they can copy them and change them without upsetting git

This would also require https://github.com/SWG-Source/swg-main/pull/10

### CODE REVIEW

**Review by Cekis — COMMENTED** [review]
servercommon.cfg has a purpose already.  The purpose for that cfg is that it should contain all "common" settings for all the servers.  The way the src is setup is that each server (planet, login, etc) start off with "common" settings, then override those settings with specific ones depending on which server is being configured.  Although I see a use for changing the way config files are setup, I would be more inclined to set them up by each server type rather than stuff all config settings that are typically unused by a user into servercommon.

**Comment by Cekis** [comment]
So, basically, I'm not really a fan of changing these, but I get there's a problem with tracking them in GIT.  I just don't know what a solid solution looks like.

**Comment by Tekaoh** [comment]
> So, basically, I'm not really a fan of changing these, but I get there's a problem with tracking them in GIT. I just don't know what a solid solution looks like.

That's fair. Maybe there's a better way to do it?

**Comment by Tekaoh** [comment]
I guess I was thinking of the file names differently. Servercommon being settings that are "common" to everyone's server. Localoptions being where you change options "locally"

**Comment by Cekis** [comment]
Well, I suppose that too could be the intended usage, but after going through the src the last few weeks I've noticed that there is a "common to all server types" mentality... i.e. "port", "maxConnections", etc.  However, maybe your proposed definition is right in this case?

**Comment by Tekaoh** [comment]
> Well, I suppose that too could be the intended usage, but after going through the src the last few weeks I've noticed that there is a "common to all server types" mentality... i.e. "port", "maxConnections", etc. However, maybe your proposed definition is right in this case?

I've noticed the same. I've been trying to become more familiar with the src lately as well.

For configs, src seems to grab the whoooole big bunch of settings from servercommon.cfg, which separates settings for different services with [Headers] like [These]. So everything under [LoginServer] is for ConfigLoginServer.cpp, everything under [PlanetServer] is for ConfigPlanetServer.cpp, etc. But everything is in the one file, and other files are included from within servercommon.cfg itself. There may even have been different config files in the past for different types of services, but they would have all been included from servercommon.cfg.

In our current configs, there are already identical [Headers] in several .cfg files and in come cases settings are set twice. Just that whatever value is parsed last is the one that is used. That's how anything in localOptions.cfg can override servercommon.cfg. I think there's already a comment about that in localOptions.cfg too. Anyways, it seems to me like that gives us the flexibility to define or redefine these files in any way we like.

Well, I'll just leave my branches and PRs open for now. Maybe if anyone else has an idea, they can branch and open a PR with a different solution and we can compare them and decide on the best one or something.

**Comment by Tekaoh** [comment]
@Cekis I thought on it and figured we might be able to combine the best of your idea as well as mine. I've moved all the default settings out to various .cfg files by type but kept the concept around localOptions where users should only use that file to override defaults. What do you think?

**Comment by Tekaoh** [comment]
As an aside to other maintainers, if we do make a decision on this, please don't make a merge commit by simply merging the pull request. I'd rather do a Squash and Merge so that it's easier to revert if ever we want to. I tried to keep it all in one commit but I don't want to do another force-push. Thanks!

**Comment by Cekis** [comment]
The multi-configuration file idea was pushed a long time ago by Seefo as well and I didn't like the idea of re configuring them.  He too wanted to do something pretty much like what you have done as well.  I'm personally not a fan of modifying the files, but now that you too are also suggesting these be modified in this way I'm starting to wonder if I'm just getting in the way of progress as opposed to doing things in the best way.  I'm going to defer any further review to Irish and Lockhart at this point and if they don't have any issue with it then sure.

**Comment by Tekaoh** [comment]
To be honest, I don't prefer having the cfg files all split into chunks like this. I like having them all in one big giant file because then it's easy to CTRL + F search for flags you want. But either way, my main thing is the untracked localOptions file. It would be great if the user could avoid editing any tracked files in order to resolve the git update problem we have currently.

**Comment by AconiteX** [comment]
I second the notion of just 1 cfg to make things less complicated. I already condensed on my box. I think a single (e.g. serverSettings.cfg) and example (e.g. defaultSettings.cfg) make the most sense. (Just my 2 cents). I don't see any legitimate reason for separating them out and it surely makes it more confusing for those unfamiliar with the configuration hierarchy and setup.

**Comment by Cekis** [comment]
What if we just referenced a new file called "customOptions.cfg" and we just referenced it in localOptions.cfg... leave all files alone with exception to that single change, then it could be up to the user to add changes to that new untracked cfg file?  Otherwise, I think we're doomed to repeat the same issue (tracked cfg files are getting changed).  I don't think the game will complain if that file doesn't exist so that may be doable.

**Comment by IrishDarkshadow** [comment]
The same thing will happen with ACM related files now. If anyone updates those using the ant build_acm command their local files will change and those are tracked files too.

Seems like we just need git tracking the template versions of the cfg files rather than the active ones and then a variation on that for the ACM files.

**Comment by Tekaoh** [comment]
> What if we just referenced a new file called "customOptions.cfg" and we just referenced it in localOptions.cfg... leave all files alone with exception to that single change, then it could be up to the user to add changes to that new untracked cfg file? Otherwise, I think we're doomed to repeat the same issue (tracked cfg files are getting changed). I don't think the game will complain if that file doesn't exist so that may be doable.

Something like this might work. The only consideration that I can think of is that zones should only go in the untracked file because the way to turn them off is to comment them out. If all the zones are on in a tracked file, I don't think you can turn them off by adding more lines to an include further down.

**Comment by IrishDarkshadow** [comment]
Looks like this one isn't of any real importance at this point:

Cekis- the cfg thing is a matter of preference
Tekaoh - I'm sort of over my PRs now anyways to be honest lol.
Irish - OK, so nobody wants to do anything about cfg files being changed / consolidated / git protected to avoid conflicts due to user settings at this point. Sounds like a dead end. I'll close off the open pull request and we can revisit if / when this comes up again.

**Comment by Tekaoh** [comment]
I was quoted a little out of context here. I'm over my PRs because I'm working on a web gui for cfg in my WordPress plugin which I'll be using instead. If you don't want to use the WordPress plugin, my opinion is still that this PR as well as https://github.com/SWG-Source/swg-main/pull/10 would be the way to go

**Pull request closed without merging**
